export const birthdayPhrases = [
    "С днем рождения, любимая. Я тебя люблю!",
    "Feliz cumpleaños, querida. Te amo!",
    "Joyeux anniversaire, ma chérie. Je t'aime!",
    "Alles Gute zum Geburtstag, meine Liebe. Ich liebe dich!",
    "Buon compleanno, cara. Ti amo!",
    "Feliz aniversário, querida. Eu te amo!",
    "Happy birthday, my love. I love you!",
    "Zorionak, maitea. Maite zaitut!",
    "Palju õnne sünnipäevaks, kallis. Ma armastan sind!",
    "Tillykke med fødselsdagen, elskede. Jeg elsker dig!",
    "Gelukkige verjaardag, mijn lief. Ik hou van jou!",
    "Hyvää syntymäpäivää, rakas. Rakastan sinua!",
    "Boldog születésnapot, kedves. Szeretlek!",
    "Selamat ulang tahun, sayang. Aku cinta padamu!",
    "С днем народження, кохана. Я тебе люблю!",
    "Chúc mừng sinh nhật, em yêu. Anh yêu em!",
    "お誕生日おめでとう、愛してるよ！",
    "생일 축하해, 내 사랑. 사랑해!",
    "生日快乐，亲爱的。我爱你！",
    "Днем народження, кохана. Я тебе люблю!",
    "Eid milad saeed, habibi. Ana behibek!",
    "Χρόνια πολλά, αγάπη μου. Σ' αγαπώ!",
    "С днем народження, кохана. Я тебе кохаю!",
    "יום הולדת שמח, אהובה. אני אוהבת אותך!",
    "Gelukkige verjaardag, my lief. Ek is lief vir jou!",
    "Grattis på födelsedagen, älskling. Jag älskar dig!",
    "Chúc mừng sinh nhật, em yêu. Anh yêu em!",
    "Selamat hari lahir, sayang. Aku cinta padamu!",
    "¡Cumpleaños feliz, mi amor. Te quiero!",
    "Joyeux anniversaire, mon amour. Je t'aime!",
    "Buon compleanno, amore mio. Ti amo!",
    "С днем рождения, дорогая. Ты в моем сердце!",
    "Herzlichen Glückwunsch zum Geburtstag, meine Liebe. Ich liebe dich!",
    "¡Feliz cumpleaños, mi amor. Te quiero mucho!",
    "Χαρούμενα γενέθλια, αγάπη μου. Σ' αγαπώ!",
    "С днем народження, моя кохана. Я тебе люблю!",
    "生日快乐，亲爱的。我永远爱你！",
    "Hyvää syntymäpäivää, rakas. Olet sydämessäni!",
    "Grattis på födelsedagen, älskling. Jag älskar dig så mycket!",
    "Boldog születésnapot, szerelmem. Imádlak!",
    "Herzlichen Glückwunsch zum Geburtstag, mein Schatz. Ich liebe dich!",
    "Buon compleanno, amore mio. Sei nel mio cuore!",
    "生日快樂，親愛的。我愛你！",
    "Glücklicher Geburtstag, meine Liebe. Du bist in meinem Herzen!",
    "С днем народження, кохана. Ти в моєму серці!",
    "Selamat hari lahir, sayang. Aku cinta padamu selamanya!",
    "פאַרצינגן צו די געבוירטן טאָג, מײַן ליב. איך האָב דיך!",
]